/*
 * @Author: 飞
 * @Date: 2021-08-20 11:26:28
 * @LastEditTime: 2021-08-24 13:41:52
 * @FilePath: \you-shop1\src\views\MerchantSettled\data.js
 * @Describe: 
 */






export default () => {
    const zfb_data = [
        { name: "美食(餐饮/食品)", val: "2015050700000000", type: "ZFB" },
        { name: "教育培训(教育/培训)", val: "2016042200000148", type: "ZFB" },
        { name: "生活服务(生活/家居)", val: "2015063000020189", type: "ZFB" },
        { name: "医疗健康(医疗)", val: "2016062900190296", type: "ZFB" },
        { name: "政府/社会组织(事业单位)", val: "2016062900190371", type: "ZFB" },
        { name: "专业销售/批发(线下零售)", val: "2016062900190337", type: "ZFB" },
        { name: "航旅(票务/旅游)", val: "2015080600000001", type: "ZFB" },
        { name: "休闲娱乐(娱乐/健身服务)", val: "2015062600004525", type: "ZFB" },
        { name: "购物(电商/团购)", val: "2015062600002758", type: "ZFB" },
        { name: "爱车(交通运输服务类)", val: "2016062900190124", type: "ZFB" },
        { name: "超市便利店(线下零售)", val: "2015091000052157", type: "ZFB" }
    ];
    const wx_data = [
        { name: "快餐(餐饮)", val: "557", type: "WX" },
        { name: "火锅(餐饮)", val: "555", type: "WX" },
        { name: "烧烤(餐饮)", val: "556", type: "WX" },
        { name: "小吃/熟食(餐饮)", val: "560", type: "WX" },
        { name: "其他中餐(餐饮)", val: "551", type: "WX" },
        { name: "日韩/东南亚菜(餐饮)", val: "553", type: "WX" },
        { name: "西餐(餐饮)", val: "552", type: "WX" },
        { name: "咖啡厅(餐饮)", val: "554", type: "WX" },
        { name: "甜品饮品(餐饮)", val: "562", type: "WX" },
        { name: "烘焙糕点(餐饮)", val: "561", type: "WX" },
        { name: "便利店(线下零售)", val: "209", type: "WX" },
        { name: "食品生鲜(线下零售)", val: "292", type: "WX" },
        { name: "数码电器/电脑办公(线下零售)", val: "319", type: "WX" },
        { name: "家具建材/家居厨具(线下零售)", val: "293", type: "WX" },
        { name: "服饰箱包(线下零售)", val: "297", type: "WX" },
        { name: "运动户外(线下零售)", val: "116", type: "WX" },
        { name: "美妆个护(线下零售)", val: "294", type: "WX" },
        { name: "母婴用品/儿童玩具(线下零售)", val: "129", type: "WX" },
        { name: "计生用品(线下零售)", val: "123", type: "WX" },
        { name: "图书音像/文具乐器(线下零售)", val: "323", type: "WX" },
        { name: "钟表眼镜(线下零售)", val: "298", type: "WX" },
        { name: "宠物/宠物用品(线下零售)", val: "305", type: "WX" },
        { name: "礼品鲜花/农资绿植(线下零售)", val: "295", type: "WX" },
        { name: "批发业(线下零售)", val: "586", type: "WX" },
        { name: "婚庆/摄影(居民生活/商业服务)", val: "299", type: "WX" },
        { name: "丧仪殡葬服务(居民生活/商业服务)", val: "568", type: "WX" },
        { name: "搬家/回收(居民生活/商业 服务)", val: "569", type: "WX" },
        { name: "宠物医院(居民生活/商业服务)", val: "570", type: "WX" },
        { name: "咨询/法律咨询/金融咨询等(居民生活/商业服务)", val: "143", type: "WX" },
        { name: "装饰/设计(居民生活/商业 服务)", val: "306", type: "WX" },
        { name: "家政/维修服务(居民生活/商业 服务)", val: "320", type: "WX" },
        { name: "广告/会展/活动策划(居民生活/商业 服务)", val: "321", type: "WX" },
        { name: "职业社交/婚介/交友(居民生活/商业 服务)", val: "157", type: "WX" },
        { name: "苗木种植/园林绿化(居民生活/商业服务)", val: "324", type: "WX" },
        { name: "娱乐票务(休闲娱乐)", val: "307", type: "WX" },
        { name: "院线影城(休闲娱乐)", val: "578", type: "WX" },
        { name: "演出赛事(休闲娱乐)", val: "579", type: "WX" },
        { name: "运动健身场馆(休闲娱乐)", val: "148", type: "WX" },
        { name: "美发/美容/美甲店(休闲娱乐)", val: "580", type: "WX" },
        { name: "俱乐部/休闲会所(休闲娱乐)", val: "300", type: "WX" },
        { name: "游艺厅/KTV/网吧(休闲娱乐)", val: "149", type: "WX" },
        { name: "酒吧(休闲娱乐)", val: "577", type: "WX" },
        { name: "汽车用品(交通运输服务)", val: "296", type: "WX" },
        { name: "汽车美容/维修保养(交通运输服务)", val: "567", type: "WX" },
        { name: "游戏(网络媒体/计算机服务/游戏)", val: "502", type: "WX" },
        { name: "软件/建站/技术开发(网络媒体/计算机服务/游戏)", val: "302", type: "WX" },
        { name: "网络推广/网络广告(网络媒体/计算 机服务/游戏)", val: "303", type: "WX" },
        { name: "教育/培训/考试缴费/学费(教育/医疗)", val: "147", type: "WX" },
        { name: "保健器械/医疗器械/非处方药品(教育/医疗)", val: "322", type: "WX" },
        { name: "私立/民营医院/诊所(教育/医疗)", val: "230", type: "WX" },
        { name: "话费通讯(生活缴费)", val: "155", type: "WX" },
        { name: "生活缴费(生活缴费)", val: "309", type: "WX" },
        { name: "财经资讯(金融)", val: "242", type: "WX" },
        { name: "旅馆/酒店/度假区(交通出行/票务旅游)", val: "301", type: "WX" },
        { name: "铁路客运(交通出行/票务旅游)", val: "308", type: "WX" },
        { name: "加油(交通出行/票务 旅游)", val: "340", type: "WX" },
        { name: "其他行业(其他)", val: "158", type: "WX" }];
    // 企业
    const wx_data_enterprise = [
        { name: "快餐(餐饮)", val: "545", type: "WX" },
        { name: "火锅(餐饮)", val: "543", type: "WX" },
        { name: "烧烤(餐饮)", val: "544", type: "WX" },
        { name: "小吃/熟食(餐饮)", val: "548", type: "WX" },
        { name: "其他中餐(餐饮)", val: "539", type: "WX" },
        { name: "日韩/东南亚菜(餐饮)", val: "541", type: "WX" },
        { name: "西餐(餐饮)", val: "540", type: "WX" },
        { name: "咖啡厅(餐饮)", val: "542", type: "WX" },
        { name: "甜品饮品(餐饮)", val: "550", type: "WX" },
        { name: "烘焙糕点(餐饮)", val: "549", type: "WX" },
        { name: "超市(线下零售)", val: "204", type: "WX" },
        { name: "便利店(线下零售)", val: "205", type: "WX" },
        { name: "百货(线下零售)", val: "207", type: "WX" },
        { name: "自动贩卖机(线下零售)", val: "206", type: "WX" },
        { name: "食品生鲜(线下零售)", val: "270", type: "WX" },
        { name: "数码电器/电脑办公(线下零售)", val: "310", type: "WX" },
        { name: "家具建材/家居厨具(线下零售)", val: "266", type: "WX" },
        { name: "服饰箱包(线下零售)", val: "271", type: "WX" },
        { name: "运动户外(线下零售)", val: "6", type: "WX" },
        { name: "美妆个护(线下零售)", val: "267", type: "WX" },
        { name: "母婴用品/儿童玩具(线下零售)", val: "19", type: "WX" },
        { name: "计生用品(线下零售)", val: "13", type: "WX" },
        { name: "黄金珠宝(线下零售)", val: "9", type: "WX" },
        { name: "礼品鲜花/农资绿植(线下零售)", val: "272", type: "WX" },
        { name: "宠物/宠物用品(线下零售)", val: "284", type: "WX" },
        { name: "钟表眼镜(线下零售)", val: "268", type: "WX" },
        { name: "批发业(线下零售)", val: "585", type: "WX" },
        { name: "图书音像/文具乐器(线下零售)", val: "315", type: "WX" },
        { name: "线上商超(网上购物)", val: "203", type: "WX" },
        { name: "物流/快递公司(居民生活/商业服务)", val: "70", type: "WX" },
        { name: "家政/维修服务(居民生活/商业 服务)", val: "311", type: "WX" },
        { name: "婚庆/摄影(居民生活/商业 服务)", val: "273", type: "WX" },
        { name: "丧仪殡葬服务(居民生活/商业服务)", val: "564", type: "WX" },
        { name: "搬家/回收(居民生活/商业服务)", val: "565", type: "WX" },
        { name: "共享服务(居民生活/商业服务)", val: "538", type: "WX" },
        { name: "宠物医院(居民生活/商业服务)", val: "566", type: "WX" },
        { name: "苗木种植/园林绿化(居民生活/商业 服务)", val: "317", type: "WX" },
        { name: "装饰/设计(居民生活/商业 服务)", val: "289", type: "WX" },
        { name: "广告/会展/活动策划(居民生活/商业 服务)", val: "312", type: "WX" },
        { name: "咨询/法律咨询/金融咨询等(居民生活/商业 服务)", val: "42", type: "WX" },
        { name: "人才中介机构/招聘(居民生活/商业服务)", val: "93", type: "WX" },
        { name: "职业社交/婚介/交友(居民生活/商业服务)", val: "94", type: "WX" },
        { name: "房地产(居民生活/商业服务)", val: "316", type: "WX" },
        { name: "娱乐票务(休闲娱乐)", val: "281", type: "WX" },
        { name: "院线影城(休闲娱乐)", val: "572", type: "WX" },
        { name: "演出赛事(休闲娱乐)", val: "573", type: "WX" },
        { name: "运动健身场馆(休闲娱乐)", val: "54", type: "WX" },
        { name: "美发/美容/美甲店(休闲娱乐)", val: "574", type: "WX" },
        { name: "俱乐部/休闲会所(休闲娱乐)", val: "280", type: "WX" },
        { name: "游艺厅/KTV/网吧(休闲娱乐)", val: "56", type: "WX" },
        { name: "酒吧(休闲娱乐)", val: "571", type: "WX" },
        { name: "租车(交通出行/票务旅游)", val: "77", type: "WX" },
        { name: "机票/机票代理(交通出行/票务旅游)", val: "274", type: "WX" },
        { name: "铁路客运(交通出行/票务旅游)", val: "283", type: "WX" },
        { name: "高速收费(交通出行/票务 旅游)", val: "610", type: "WX" },
        { name: "城市公共交通(交通出行/票务旅游)", val: "288", type: "WX" },
        { name: "加油(交通出行/票务旅游)", val: "259", type: "WX" },
        { name: "停车缴费(交通出行/票务旅游)", val: "287", type: "WX" },
        { name: "汽车用品(交通出行/票务旅游)", val: "269", type: "WX" },
        { name: "汽车美容/维修保养(交通出行/票务 旅游)", val: "563", type: "WX" },
        { name: "船舶/海运服务(交通出行/票务 旅游)", val: "75", type: "WX" },
        { name: "景区(交通出行/票务 旅游)", val: "354", type: "WX" },
        { name: "旅馆/酒店/度假区(交通出行/票务 旅游)", val: "275", type: "WX" },
        { name: "旅行社(交通出行/票务旅游)", val: "23", type: "WX" },
        { name: "在线图书/视频/音乐(网络媒体/计算机服务/游戏)", val: "276", type: "WX" },
        { name: "门户/资讯/论坛(网络媒体/计算机服务/游戏)", val: "104", type: "WX" },
        { name: "游戏(网络媒体/计算机服务/游戏)", val: "501", type: "WX" },
        { name: "网络直播(网络媒体/计算 机服务/游戏)", val: "521", type: "WX" },
        { name: "软件/建站/技术开发(网络媒体/计算 机服务/游戏)", val: "277", type: "WX" },
        { name: "网络推广/网络广告(网络媒体/计算 机服务/游戏)", val: "278", type: "WX" },
        { name: "团购服务平台(网上服务平台)", val: "2", type: "WX" },
        { name: "综合生活服务平台(网上服务平台)", val: "95", type: "WX" },
        { name: "旅游服务平台(网上服务平台)", val: "24", type: "WX" },
        { name: "订餐服务平台(网上服务平台)", val: "522", type: "WX" },
        { name: "教育/培训/考试缴费/学费(教育/医疗)", val: "52", type: "WX" },
        { name: "私立院校(教育/医疗)", val: "53", type: "WX" },
        { name: "保健器械/医疗器械/非处方药品(教育/医疗)", val: "314", type: "WX" },
        { name: "保健信息咨询平台(教育/医疗)", val: "282", type: "WX" },
        { name: "私立/民营医院/诊所(教育/医疗)", val: "66", type: "WX" },
        { name: "挂号平台(教育/医疗)", val: "67", type: "WX" },
        { name: "电信运营商(生活缴费)", val: "80", type: "WX" },
        { name: "宽带收费(生活缴费)", val: "81", type: "WX" },
        { name: "话费通讯(生活缴费)", val: "92", type: "WX" },
        { name: "有线电视缴费(生活缴费)", val: "58", type: "WX" },
        { name: "物业管理费(生活缴费)", val: "60", type: "WX" },
        { name: "水电煤缴费/交通罚款等生活缴费(生活缴费)", val: "57", type: "WX" },
        { name: "其他生活缴费(生活缴费)", val: "62", type: "WX" },
        { name: "财经资讯(金融)", val: "96", type: "WX" },
        { name: "股票软件类(金融)", val: "97", type: "WX" },
        { name: "保险业务(金融)", val: "318", type: "WX" },
        { name: "众筹(金融)", val: "112", type: "WX" },
        { name: "信用还款(金融)", val: "326", type: "WX" },
        { name: "非文物类收藏品(收藏/拍卖)", val: "31", type: "WX" },
        { name: "文物经营/文物复制品销售(收藏/拍卖)", val: "285", type: "WX" },
        { name: "拍卖/典当(收藏/拍卖)", val: "325", type: "WX" },
        { name: "其他行业(其他)", val: "111", type: "WX" }
    ]
    return { zfb_data, wx_data, wx_data_enterprise }
}